// import { blue } from "react-native-reanimated/lib/typescript/Colors";

export const utilities = [
  {
    id: "water",
    name: "Water",
    icon: "💧",
    color: "blue",
    backgroundColor: "#dbeafe",
    borderColor: "#3b82f6",
    provider: "Manila Water",
    backgroundColor2: "blue-50",
  },
  {
    id: "electricity",
    name: "Electricity",
    icon: "⚡",
    color: "amber",
    backgroundColor: "#fef3c7",
    borderColor: "#f59e0b",
    provider: "Meralco",
    backgroundColor2: "amber-50",
  },
  {
    id: "kitchenGas",
    name: "Kitchen Gas",
    icon: "🔥",
    color: "orange",
    backgroundColor: "#fed7aa",
    borderColor: "#fb923c",
    provider: "Shell",
    backgroundColor2: "orange-50",
  },

  {
    id: "fuel",
    name: "Transport Fuel",
    icon: "⛽",
    color: "red",
    backgroundColor: "#feadaa",
    borderColor: "#f91616",
    provider: "Shell",
    backgroundColor2: "red-50",
  },
  {
    id: "grocery",
    name: "Groceries",
    icon: "🛒",
    color: "green",
    backgroundColor: "#bbf7d0",
    borderColor: "#22c55e",
    provider: "SM Supermarket",
    backgroundColor2: "green-50",
  },

  {
    id: "miscellaneous",
    name: "Miscellaneous",
    icon: "📦",
    color: "purple",
    backgroundColor: "#ceace5",
    borderColor: "#ad65e4",
    provider: "Other",
    backgroundColor2: "purple-50",
  },
];